/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinal;

/**
 *
 * @author Rodrigo
 */
public class JCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form JCalculadora
     */
    public JCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    String sinal;
    private double a;
    private double b;
    private boolean sPc;
    private String valor = "";
    private String escolha = "";
    
    Calculadora calc = new Calculadora();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnAPAGAR = new javax.swing.JButton();
        btnVIRGULA = new javax.swing.JButton();
        btnQUATRO = new javax.swing.JButton();
        btnCINCO = new javax.swing.JButton();
        btnSEIS = new javax.swing.JButton();
        btnTRES = new javax.swing.JButton();
        btnUM = new javax.swing.JButton();
        btnDOIS = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnDIVIDIR = new javax.swing.JButton();
        btnIGUAL = new javax.swing.JButton();
        btnMULTIPLICAR = new javax.swing.JButton();
        btnSOMAR = new javax.swing.JButton();
        btnSUBTRAIR = new javax.swing.JButton();
        btnSETE = new javax.swing.JButton();
        btnOITO = new javax.swing.JButton();
        btnNOVE = new javax.swing.JButton();
        btnPORCENTAGEM = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        CPR = new javax.swing.JTextField();

        jButton17.setText("jButton17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCE.setBackground(new java.awt.Color(255, 204, 0));
        btnCE.setForeground(new java.awt.Color(255, 51, 51));
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(255, 102, 153));
        btnC.setText("C");
        btnC.setMaximumSize(new java.awt.Dimension(45, 23));
        btnC.setMinimumSize(new java.awt.Dimension(45, 23));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnAPAGAR.setBackground(new java.awt.Color(255, 0, 0));
        btnAPAGAR.setText("←");
        btnAPAGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAPAGARActionPerformed(evt);
            }
        });

        btnVIRGULA.setText(".");
        btnVIRGULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIRGULAActionPerformed(evt);
            }
        });

        btnQUATRO.setText("4");
        btnQUATRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQUATROActionPerformed(evt);
            }
        });

        btnCINCO.setText("5");
        btnCINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCINCOActionPerformed(evt);
            }
        });

        btnSEIS.setText("6");
        btnSEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEISActionPerformed(evt);
            }
        });

        btnTRES.setText("3");
        btnTRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTRESActionPerformed(evt);
            }
        });

        btnUM.setText("1");
        btnUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUMActionPerformed(evt);
            }
        });

        btnDOIS.setText("2");
        btnDOIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOISActionPerformed(evt);
            }
        });

        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnDIVIDIR.setBackground(new java.awt.Color(153, 153, 255));
        btnDIVIDIR.setText("/");
        btnDIVIDIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDIVIDIRActionPerformed(evt);
            }
        });

        btnIGUAL.setBackground(new java.awt.Color(51, 102, 0));
        btnIGUAL.setText("=");
        btnIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIGUALActionPerformed(evt);
            }
        });

        btnMULTIPLICAR.setBackground(new java.awt.Color(255, 255, 51));
        btnMULTIPLICAR.setText("*");
        btnMULTIPLICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMULTIPLICARActionPerformed(evt);
            }
        });

        btnSOMAR.setBackground(new java.awt.Color(0, 255, 204));
        btnSOMAR.setText("+");
        btnSOMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSOMARActionPerformed(evt);
            }
        });

        btnSUBTRAIR.setBackground(new java.awt.Color(255, 0, 255));
        btnSUBTRAIR.setText("-");
        btnSUBTRAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUBTRAIRActionPerformed(evt);
            }
        });

        btnSETE.setText("7");
        btnSETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSETEActionPerformed(evt);
            }
        });

        btnOITO.setText("8");
        btnOITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOITOActionPerformed(evt);
            }
        });

        btnNOVE.setText("9");
        btnNOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNOVEActionPerformed(evt);
            }
        });

        btnPORCENTAGEM.setBackground(new java.awt.Color(0, 102, 102));
        btnPORCENTAGEM.setText("%");
        btnPORCENTAGEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPORCENTAGEMActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 0, 51));
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOITO, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSOMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAPAGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDIVIDIR, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSETE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQUATRO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPORCENTAGEM, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDOIS, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(btnCINCO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVIRGULA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSEIS, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(btnTRES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSUBTRAIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMULTIPLICAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIGUAL, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CPR, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(CPR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAPAGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDIVIDIR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSETE, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOITO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSOMAR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMULTIPLICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDOIS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUM, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTRES, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSUBTRAIR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVIRGULA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPORCENTAGEM, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDIVIDIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDIVIDIRActionPerformed
      if (!(CPR.getText().equals("")  || CPR.getText().equals(escolha)  || valor.equals("")))  {
        a = Double.parseDouble(valor);
        escolha = "/";
        valor="";
        CPR.setText(escolha);
        sPc = false;
    }
    }//GEN-LAST:event_btnDIVIDIRActionPerformed

    private void btnIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIGUALActionPerformed
     if(!escolha.equals("")){
         b = Double.parseDouble(valor);
         double resultado = 0;
         switch (escolha){
             case "+":
                 resultado = a+b;
                 CPR.setText(String.valueOf(resultado));
                 lblMsg.setText(String.valueOf(a + "+" + b));
                 escolha = "";
                 valor = "";    
                 sPc = false;
                     break;
                     
                     case "-":
                         resultado = a-b;
                 CPR.setText(String.valueOf(resultado));
                 lblMsg.setText(String.valueOf(a + "-" + b));
                 escolha = "";
                 valor = "";    
                 sPc = false;
                     break;
                     
                     case "*":
                         resultado = a*b;
                 CPR.setText(String.valueOf(resultado));
                 lblMsg.setText(String.valueOf(a + "*" + b));
                 escolha = "";
                 valor = "";    
                 sPc = false;
                     break;
                     
                     case "/":  
                         try{
                             resultado = a/b;
                             if(String.valueOf(resultado).equalsIgnoreCase("Infinito")){
                                 throw new ArithmeticException();
                             }
                             CPR.setText(String.valueOf(resultado));
                             lblMsg.setText(String.valueOf(a + "/" + b));
                 escolha = "";
                 valor = "";    
                 sPc = false;
                         }catch (ArithmeticException e) {
                 CPR.setText("Não pode ser dividido por Zero");
                 escolha = "";
                 valor = "";    
                 sPc = false;
                         }
                        
                     break;
                     case "%":
                         resultado = a%b;
                 CPR.setText(String.valueOf(resultado));
                 lblMsg.setText(String.valueOf(a + "%" + b));
                 escolha = "";
                 valor = "";    
                 sPc = false;
                     break;

         }
     }
      
         
        
    }//GEN-LAST:event_btnIGUALActionPerformed

    private void btnAPAGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAPAGARActionPerformed
         String value = CPR.getText();
          int length = value.length();
          
          if(length > 0){
              StringBuilder builder = new StringBuilder(value);
              builder.deleteCharAt(length - 1);
              CPR.setText(builder.toString());
              
          }
    }//GEN-LAST:event_btnAPAGARActionPerformed

    private void btnMULTIPLICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMULTIPLICARActionPerformed
        if (CPR.getText().equals("")){
            escolha = "-";
            valor = "-";
            CPR.setText(escolha);
        }
        else if (!(CPR.getText().equals("")  || CPR.getText().equals(escolha)  || valor.equals("")))  {
        a = Double.parseDouble(valor);
        escolha = "*";
        valor="";
        CPR.setText(escolha);
        sPc = false;
    }
    }//GEN-LAST:event_btnMULTIPLICARActionPerformed

    private void btnSUBTRAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUBTRAIRActionPerformed
    if (!(CPR.getText().equals("")  || CPR.getText().equals(escolha)  || valor.equals("")))  {
        a = Double.parseDouble(valor);
        escolha = "-";
        valor="";
        CPR.setText(escolha);
        sPc = false;
    }
    }//GEN-LAST:event_btnSUBTRAIRActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
     valor+="0";
        CPR.setText(valor);
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUMActionPerformed
        valor+="1";
        CPR.setText(valor);
    }//GEN-LAST:event_btnUMActionPerformed

    private void btnDOISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOISActionPerformed
       valor+="2";
        CPR.setText(valor);
    }//GEN-LAST:event_btnDOISActionPerformed

    private void btnTRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTRESActionPerformed
         valor+="3";
        CPR.setText(valor);
    }//GEN-LAST:event_btnTRESActionPerformed

    private void btnQUATROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQUATROActionPerformed
       valor+="4";
        CPR.setText(valor);
    }//GEN-LAST:event_btnQUATROActionPerformed

    private void btnCINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCINCOActionPerformed
     valor+="5";
        CPR.setText(valor);
    }//GEN-LAST:event_btnCINCOActionPerformed

    private void btnSEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEISActionPerformed
      valor+="6";
        CPR.setText(valor);
    }//GEN-LAST:event_btnSEISActionPerformed

    private void btnSETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSETEActionPerformed
    valor+="7";
        CPR.setText(valor);
    }//GEN-LAST:event_btnSETEActionPerformed

    private void btnOITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOITOActionPerformed
       valor+="8";
        CPR.setText(valor);
    }//GEN-LAST:event_btnOITOActionPerformed

    private void btnNOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOVEActionPerformed
      valor+="9";
        CPR.setText(valor);
    }//GEN-LAST:event_btnNOVEActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
      CPR.setText("");
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        CPR.setText("");
     CPR.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnSOMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSOMARActionPerformed
        if (!(CPR.getText().equals("")  || CPR.getText().equals(escolha)  || valor.equals("")))  {
        a = Double.parseDouble(valor);
        escolha = "+";
        valor="";
        CPR.setText(escolha);
        sPc = false;
    }
    }//GEN-LAST:event_btnSOMARActionPerformed

    private void btnPORCENTAGEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPORCENTAGEMActionPerformed
                if (!(CPR.getText().equals("") || CPR.getText().equals(escolha) || valor.equals(""))) {
            a = Double.parseDouble(valor);
            escolha = "%";
            valor = "";
            CPR.setText(escolha);
            sPc = false;
        }
    }//GEN-LAST:event_btnPORCENTAGEMActionPerformed

    private void btnVIRGULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIRGULAActionPerformed
        if(sPc == false);
        valor+=".";
        CPR.setText(valor);
        sPc = true;
    }//GEN-LAST:event_btnVIRGULAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPR;
    private javax.swing.JButton btnAPAGAR;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCINCO;
    private javax.swing.JButton btnDIVIDIR;
    private javax.swing.JButton btnDOIS;
    private javax.swing.JButton btnIGUAL;
    private javax.swing.JButton btnMULTIPLICAR;
    private javax.swing.JButton btnNOVE;
    private javax.swing.JButton btnOITO;
    private javax.swing.JButton btnPORCENTAGEM;
    private javax.swing.JButton btnQUATRO;
    private javax.swing.JButton btnSEIS;
    private javax.swing.JButton btnSETE;
    private javax.swing.JButton btnSOMAR;
    private javax.swing.JButton btnSUBTRAIR;
    private javax.swing.JButton btnTRES;
    private javax.swing.JButton btnUM;
    private javax.swing.JButton btnVIRGULA;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel lblMsg;
    // End of variables declaration//GEN-END:variables
}
